import type { Lang } from './site';

export type Dict = typeof bn;

export const bn = {
  htmlLang: 'bn',
  dir: 'ltr',
  nav: {
    home: 'হোম',
    about: 'আমাদের সম্পর্কে',
    practice: 'অনুশীলনী বিতর্ক',
    motions: 'মোশন ব্যাংক',
    campus: 'ক্যাম্পাস কানেক্ট',
    events: 'আয়োজন',
    team: 'টিম',
    blog: 'ব্লগ',
    partners: 'অংশীদার',
    contact: 'যোগাযোগ',
    join: 'সদস্য হও',
    more: 'আরও',
  },
  common: {
    readMore: 'বিস্তারিত দেখো',
    viewAll: 'সবগুলো দেখো',
    back: 'ফিরে যাও',
    switchLang: 'English',
    toDark: 'ডার্ক মোডে যাও',
    toLight: 'লাইট মোডে যাও',
    dark: 'ডার্ক',
    light: 'লাইট',
    openMenu: 'মেনু খোলো',
    closeMenu: 'মেনু বন্ধ করো',
    skipToContent: 'সরাসরি মূল অংশে যাও',
    copy: 'কপি করো',
    copied: 'কপি হয়েছে',
    search: 'খুঁজো',
    all: 'সব',
    noResult: 'কিছু পাওয়া যায়নি। অন্য শব্দ দিয়ে খুঁজে দেখো।',
    source: 'উৎস',
  },
  home: {
    heroEyebrow: 'বগুড়া জেলার প্রথম পেশাদার বিতর্ক সংগঠন · প্রতিষ্ঠা ০১ এপ্রিল ২০২৫',
    heroLine1: 'ভাষাকে করো অস্ত্র,',
    heroLine2: 'যুক্তিকে করো শাণিত।',
    heroBody:
      'বগুড়ার স্কুল, কলেজ ও বিশ্ববিদ্যালয়ের শিক্ষার্থীদের জন্য নিয়মিত অনুশীলনী বিতর্ক, কর্মশালা ও প্রতিযোগিতা — যুক্তিবাদী চিন্তা, গবেষণা আর সংলাপের সংস্কৃতি গড়ে তুলতে।',
    ctaJoin: 'সদস্য হও',
    ctaPractice: 'অনুশীলনী বিতর্ক দেখো',
    ctaWorkshop: 'কর্মশালা চাই',
    statsTitle: 'এক নজরে',
    statsSub: 'এপ্রিল ২০২৫ থেকে আগস্ট ২০২৬ পর্যন্ত যা হয়েছে',
    activitiesTitle: 'আমরা যা করি',
    activitiesSub: 'BDS-এর নিয়মিত কার্যক্রম',
    formatsTitle: 'বিতর্কের ধরন',
    formatsSub: 'পাঁচটি ফরম্যাটে আমরা কাজ করি',
    practiceTitle: 'সর্বশেষ অনুশীলনী বিতর্ক',
    practiceSub: 'সপ্তাহে ৩–৪টি সেশন — সবগুলোর রেকর্ড রাখা হয়',
    practiceAll: 'সবগুলো দেখো (১৯টি)',
    campusTitle: 'ক্যাম্পাস কানেক্ট',
    campusSub: 'বগুড়ার স্কুল-কলেজে বিতর্ক পৌঁছে দেওয়ার ক্যাম্পেইন',
    campusAll: 'পুরো ক্যাম্পেইন দেখো',
    eventsTitle: 'বড় আয়োজন',
    eventsSub: 'যেসব আয়োজন BDS-এর পথচলা তৈরি করেছে',
    visionEyebrow: 'সংগঠনের ভাবনা',
    teamTitle: 'যাঁদের নিয়ে BDS',
    teamSub: 'উপদেষ্টা, মেন্টর ও কার্যনির্বাহী কমিটি',
    partnersTitle: 'যাঁদের সাথে কাজ করেছি',
    partnersSub: 'সহ-আয়োজক, প্রতিষ্ঠান ও পৃষ্ঠপোষক',
    joinTitle: 'যুক্তি দিয়ে শুরু হোক তোমার পথচলা',
    joinBody: 'বিতর্ক আগে না করলেও চলবে। দরকার শুধু শেখার আগ্রহ আর মঞ্চে দাঁড়ানোর সাহস।',
  },
  practice: {
    title: 'অনুশীলনী বিতর্ক আর্কাইভ',
    sub: 'BDS-এর সবচেয়ে নিয়মিত কার্যক্রম। প্রতিটি সেশনের বিষয়, বিজয়ী পক্ষ, শ্রেষ্ঠ বক্তা ও বিচারকের রেকর্ড।',
    total: 'মোট সেশন',
    traditional: 'সনাতনী',
    parliamentary: 'সংসদীয়',
    colNo: 'নং',
    colFormat: 'ধরন',
    colMotion: 'বিষয়',
    colWinner: 'বিজয়ী',
    colBest: 'শ্রেষ্ঠ বক্তা',
    colAdj: 'বিচারক',
    missing: 'রেকর্ড অনুপস্থিত',
    missingNote: 'এই সেশনের বিস্তারিত আর্কাইভে পাওয়া যায়নি। কারও কাছে রেকর্ড থাকলে আমাদের জানাও।',
  },
  motions: {
    title: 'মোশন ব্যাংক',
    sub: 'BDS-এর আয়োজনে ব্যবহৃত সব বিতর্কের বিষয় — এক জায়গায়, খুঁজে নেওয়ার মতো করে।',
    searchPlaceholder: 'বিষয় খুঁজো… (শব্দ, ধরন, আয়োজন)',
    filterFormat: 'ধরন',
    filterTopic: 'বিষয়',
    count: 'টি বিষয়',
    usedIn: 'ব্যবহৃত হয়েছে',
  },
  campus: {
    title: 'ক্যাম্পাস কানেক্ট',
    sub: 'বগুড়ার স্কুল, কলেজ ও উপজেলায় বিতর্ক পৌঁছে দেওয়ার ধারাবাহিক ক্যাম্পেইন।',
    curriculum: 'প্রতিটি কর্মশালায় যা থাকে',
    requestTitle: 'আপনার প্রতিষ্ঠানে কর্মশালা চান?',
    requestBody: 'BDS বিনামূল্যে বিতর্ক কর্মশালা আয়োজন করে। প্রতিষ্ঠানের পক্ষ থেকে যোগাযোগ করুন।',
    colDate: 'তারিখ',
    colInstitution: 'প্রতিষ্ঠান',
    colArea: 'এলাকা',
    colAttendance: 'অংশগ্রহণ',
    colNote: 'বিশেষত্ব',
  },
  about: {
    title: 'আমাদের সম্পর্কে',
    sub: 'শূন্য থেকে এক জেলার কেন্দ্রীয় বিতর্ক সংগঠন — এক বছর চার মাসের পথচলা।',
    purposeTitle: 'লক্ষ্য ও উদ্দেশ্য',
    purposeNote: 'প্রতিষ্ঠাকালীন ঘোষণা অনুযায়ী',
    timelineTitle: 'পথচলা',
    timelineSub: 'এপ্রিল ২০২৫ থেকে আগস্ট ২০২৬',
  },
  team: {
    title: 'যাঁদের নিয়ে BDS',
    sub: 'উপদেষ্টা, মেন্টর, কার্যনির্বাহী কমিটি এবং যাঁরা প্রতি সপ্তাহে মঞ্চে দাঁড়ান।',
    debatersTitle: 'সক্রিয় বিতার্কিক',
    debatersSub: 'অনুশীলনী বিতর্কে নিয়মিত অংশ নেওয়া সদস্যদের আংশিক তালিকা',
  },
  bestSpeakers: {
    title: 'শ্রেষ্ঠ বক্তারা',
    sub: 'প্রতিটি অনুশীলনী সেশনের শ্রেষ্ঠ বক্তা — ২০২৫–২৬ সালের সংকলিত রেকর্ড।',
  },
  events: {
    title: 'আয়োজন',
    sub: 'প্রতিযোগিতা, কর্মশালা ও শো ডিবেট — প্রতিটির পূর্ণ রেকর্ড।',
    details: 'বিস্তারিত',
    motionsLabel: 'বিতর্কের বিষয়',
    resultsLabel: 'ফলাফল',
    teamsLabel: 'অংশগ্রহণকারী দল',
    adjLabel: 'বিচারকমণ্ডলী',
  },
  join: {
    title: 'সদস্য হও',
    sub: 'BDS-তে যুক্ত হতে অভিজ্ঞতা লাগে না। দরকার শেখার আগ্রহ আর মঞ্চে দাঁড়ানোর সাহস।',
    benefits: 'সদস্য হলে যা পাবে',
    typesTitle: 'তিন ধরনের সদস্যপদ',
    formTitle: 'আবেদন ফর্ম',
    formNote:
      'ফর্মটি এখনো কোনো সার্ভারে যুক্ত নয় — README-র "Form সংযুক্ত করা" অংশ দেখে Netlify Forms চালু করো, দুই মিনিটের কাজ।',
    name: 'পূর্ণ নাম',
    institution: 'প্রতিষ্ঠান',
    classYear: 'শ্রেণি / বর্ষ',
    phone: 'ফোন নম্বর',
    email: 'ইমেইল',
    area: 'এলাকা',
    fb: 'ফেসবুক প্রোফাইল লিংক',
    experience: 'বিতর্কের অভিজ্ঞতা',
    expNew: 'একদম নতুন',
    expSchool: 'স্কুল পর্যায়ে করেছি',
    expRegular: 'নিয়মিত করি',
    interests: 'আগ্রহের ধরন',
    why: 'কেন যুক্ত হতে চাও?',
    submit: 'আবেদন পাঠাও',
  },
  contact: {
    title: 'যোগাযোগ',
    sub: 'কর্মশালা, প্রতিযোগিতা, সহযোগিতা বা সদস্যপদ — যেকোনো বিষয়ে লিখতে পারো।',
    infoTitle: 'যোগাযোগের তথ্য',
    formTitle: 'বার্তা পাঠাও',
    subject: 'বিষয়',
    subjects: ['সাধারণ', 'কর্মশালার অনুরোধ', 'প্রতিযোগিতা', 'স্পন্সরশিপ / সহযোগিতা', 'সদস্যপদ'],
    message: 'বার্তা',
    send: 'পাঠাও',
    address: 'ঠিকানা',
    office: 'অফিস',
    phone: 'ফোন',
    email: 'ইমেইল',
    social: 'সোশ্যাল',
  },
  partners: {
    title: 'অংশীদার ও সহযোগী',
    sub: 'যেসব সংগঠন, প্রতিষ্ঠান ও পৃষ্ঠপোষকের সাথে BDS কাজ করেছে।',
    kinds: { org: 'সংগঠন', institution: 'প্রতিষ্ঠান', sponsor: 'পৃষ্ঠপোষক', authority: 'সরকারি সংস্থার সাথে কাজ' },
  },
  buddy: {
    eyebrow: 'BDS সহায়ক',
    title: 'প্রশ্ন আছে?',
    chip: 'FAQ',
    open: 'BDS সহায়ক খোলো',
    close: 'বন্ধ করো',
    greeting: 'আসসালামু আলাইকুম! আমি BDS সহায়ক। সদস্য হওয়া, কর্মশালা বা অনুশীলনী বিতর্ক নিয়ে জিজ্ঞেস করতে পারো।',
    placeholder: 'তোমার প্রশ্ন লেখো…',
    send: 'পাঠাও',
    fallback: 'এই প্রশ্নের প্রস্তুত উত্তর এখনো নেই। যোগাযোগ পাতা থেকে সরাসরি লিখলে টিম উত্তর দেবে।',
    suggestions: 'যা জিজ্ঞেস করতে পারো',
  },
  footer: {
    blurb:
      'বগুড়া জেলার প্রথম পেশাদার ও একমাত্র জেলাভিত্তিক কেন্দ্রীয় বিতর্ক সংগঠন। তরুণদের মধ্যে যুক্তিবাদী চিন্তা, গবেষণা ও সংলাপের সংস্কৃতি গড়ে তোলাই আমাদের কাজ।',
    links: 'দ্রুত লিংক',
    community: 'কমিউনিটি',
    rights: 'সর্বস্বত্ব সংরক্ষিত',
  },
  blog: {
    title: 'ব্লগ',
    sub: 'খবর, ঘোষণা আর বিতর্ক নিয়ে লেখালেখি — BDS-এর নিজস্ব পাতা থেকে।',
    empty: 'এখনো কোনো লেখা প্রকাশিত হয়নি। শীঘ্রই আসছে।',
  },
  notFound: {
    motion: 'এই সংসদ বিশ্বাস করে যে এই পাতাটির অস্তিত্ব নেই।',
    body: 'ঠিকানাটি বদলে গেছে, নাকি কখনো ছিলই না — সে বিতর্ক অন্যদিন। আপাতত হোমপেজে ফিরে যাও।',
    cta: 'হোমপেজে ফিরে যাও',
  },
};

export const en: Dict = {
  htmlLang: 'en',
  dir: 'ltr',
  nav: {
    home: 'Home',
    about: 'About',
    practice: 'Practice Debates',
    motions: 'Motion Bank',
    campus: 'Campus Connect',
    events: 'Events',
    team: 'Team',
    blog: 'Blog',
    partners: 'Partners',
    contact: 'Contact',
    join: 'Join BDS',
    more: 'More',
  },
  common: {
    readMore: 'Read more',
    viewAll: 'View all',
    back: 'Back',
    switchLang: 'বাংলা',
    toDark: 'Switch to dark theme',
    toLight: 'Switch to light theme',
    dark: 'Dark',
    light: 'Light',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    skipToContent: 'Skip to content',
    copy: 'Copy',
    copied: 'Copied',
    search: 'Search',
    all: 'All',
    noResult: 'Nothing found. Try a different word.',
    source: 'Source',
  },
  home: {
    heroEyebrow: 'Bogura’s first professional debating organisation · founded 01 April 2025',
    heroLine1: 'Make language',
    heroLine2: 'your sharpest argument.',
    heroBody:
      'Weekly practice debates, workshops and tournaments for the students of Bogura — building a culture of reasoned thinking, research and dialogue.',
    ctaJoin: 'Join BDS',
    ctaPractice: 'See practice debates',
    ctaWorkshop: 'Request a workshop',
    statsTitle: 'At a glance',
    statsSub: 'What happened between April 2025 and August 2026',
    activitiesTitle: 'What we do',
    activitiesSub: 'The regular work of BDS',
    formatsTitle: 'Debate formats',
    formatsSub: 'We work across five formats',
    practiceTitle: 'Latest practice debates',
    practiceSub: 'Three to four sessions a week — every one of them recorded',
    practiceAll: 'See all 19',
    campusTitle: 'BDS Campus Connect',
    campusSub: 'Taking debate into the schools and colleges of Bogura',
    campusAll: 'See the whole campaign',
    eventsTitle: 'Major events',
    eventsSub: 'The events that shaped the BDS story',
    visionEyebrow: 'What we believe',
    teamTitle: 'The people behind BDS',
    teamSub: 'Advisors, mentors and the executive committee',
    partnersTitle: 'Who we have worked with',
    partnersSub: 'Co-hosts, institutions and sponsors',
    joinTitle: 'Start your journey with an argument',
    joinBody: 'No debate experience needed — just curiosity and the nerve to stand up.',
  },
  practice: {
    title: 'Practice Debate Archive',
    sub: 'The most regular BDS activity. Motion, winning side, best speaker and adjudicator for every session.',
    total: 'Total sessions',
    traditional: 'Traditional',
    parliamentary: 'Parliamentary',
    colNo: 'No.',
    colFormat: 'Format',
    colMotion: 'Motion',
    colWinner: 'Winner',
    colBest: 'Best speaker',
    colAdj: 'Adjudicator',
    missing: 'Record missing',
    missingNote: 'Details for this session were not found in the archive. If you have the record, please tell us.',
  },
  motions: {
    title: 'Motion Bank',
    sub: 'Every motion used at a BDS event — in one place, searchable.',
    searchPlaceholder: 'Search motions… (topic, word, event)',
    filterFormat: 'Format',
    filterTopic: 'Topic',
    count: ' motions',
    usedIn: 'Used at',
  },
  campus: {
    title: 'BDS Campus Connect',
    sub: 'An ongoing campaign taking debate into the schools, colleges and upazilas of Bogura.',
    curriculum: 'What every workshop covers',
    requestTitle: 'Want a workshop at your institution?',
    requestBody: 'BDS runs debate workshops free of charge. Get in touch on behalf of your school or college.',
    colDate: 'Date',
    colInstitution: 'Institution',
    colArea: 'Area',
    colAttendance: 'Attendance',
    colNote: 'Notes',
  },
  about: {
    title: 'About BDS',
    sub: 'From nothing to a district-wide debating body — sixteen months of work.',
    purposeTitle: 'Purpose',
    purposeNote: 'From the founding declaration',
    timelineTitle: 'The journey',
    timelineSub: 'April 2025 to August 2026',
  },
  team: {
    title: 'The people behind BDS',
    sub: 'Advisors, mentors, the executive committee — and the students who stand up every week.',
    debatersTitle: 'Active debaters',
    debatersSub: 'A partial list of members who regularly take part in practice debates',
  },
  bestSpeakers: {
    title: 'Best speakers',
    sub: 'Unveiling The Best Speakers (2025–26) — the best speaker from every practice session.',
  },
  events: {
    title: 'Events',
    sub: 'Tournaments, workshops and show debates — with the full record of each.',
    details: 'Details',
    motionsLabel: 'Motions',
    resultsLabel: 'Results',
    teamsLabel: 'Teams',
    adjLabel: 'Adjudicators',
  },
  join: {
    title: 'Join BDS',
    sub: 'You do not need experience to join. Curiosity and the nerve to stand up are enough.',
    benefits: 'What membership gives you',
    typesTitle: 'Three kinds of recruitment',
    formTitle: 'Application form',
    formNote:
      'This form is not wired to a server yet — see “Connecting the forms” in the README to switch on Netlify Forms. It takes two minutes.',
    name: 'Full name',
    institution: 'Institution',
    classYear: 'Class / year',
    phone: 'Phone',
    email: 'Email',
    area: 'Area',
    fb: 'Facebook profile link',
    experience: 'Debate experience',
    expNew: 'Complete beginner',
    expSchool: 'Some school-level experience',
    expRegular: 'I debate regularly',
    interests: 'Formats you are interested in',
    why: 'Why do you want to join?',
    submit: 'Send application',
  },
  contact: {
    title: 'Contact',
    sub: 'Workshops, tournaments, collaboration or membership — write to us about any of it.',
    infoTitle: 'Contact details',
    formTitle: 'Send a message',
    subject: 'Subject',
    subjects: ['General', 'Workshop request', 'Tournament', 'Sponsorship / collaboration', 'Membership'],
    message: 'Message',
    send: 'Send',
    address: 'Address',
    office: 'Office',
    phone: 'Phone',
    email: 'Email',
    social: 'Social',
  },
  partners: {
    title: 'Partners & collaborators',
    sub: 'The organisations, institutions and sponsors BDS has worked with.',
    kinds: { org: 'Organisations', institution: 'Institutions', sponsor: 'Sponsors', authority: 'Worked with public bodies' },
  },
  buddy: {
    eyebrow: 'BDS Helper',
    title: 'Any questions?',
    chip: 'FAQ',
    open: 'Open the BDS helper',
    close: 'Close',
    greeting: 'Hello! I am the BDS helper. Ask me about joining, workshops or our practice debates.',
    placeholder: 'Type your question…',
    send: 'Send',
    fallback: 'I do not have a ready answer for that yet. Write to us from the contact page and the team will reply.',
    suggestions: 'You could ask',
  },
  footer: {
    blurb:
      'Bogura’s first professional and only district-wide central debating organisation, building a culture of reasoned thinking, research and dialogue among young people.',
    links: 'Quick links',
    community: 'Community',
    rights: 'All rights reserved',
  },
  blog: {
    title: 'Blog',
    sub: 'News, announcements and writing about debate — from BDS itself.',
    empty: 'Nothing published yet. Coming soon.',
  },
  notFound: {
    motion: 'This House believes that this page does not exist.',
    body: 'Whether the address changed or never existed is a debate for another day. For now, head back home.',
    cta: 'Back to the homepage',
  },
};

export const dicts: Record<Lang, Dict> = { bn, en };
export const getDict = (lang: Lang): Dict => dicts[lang] ?? bn;
